import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:apii/modelclass.dart';

void main() {
  runApp(MaterialApp(
    home: MyWidget(),
    debugShowCheckedModeBanner: false,
  ));
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  late Future<List<Autogenerated>> futureAlbum;

  @override
  void initState() {
    super.initState();
    futureAlbum = fetchAlbum();
  }

  Future<List<Autogenerated>> fetchAlbum() async {
    final response =
        await http.get(Uri.parse('https://fakestoreapi.com/products'));

    if (response.statusCode == 200) {
      return Autogenerated.fromJsonList(
          jsonDecode(response.body) as List<dynamic>);
    } else {
      throw Exception('Failed to load products');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Shopping mart"),
        actions: [
          Icon(Icons.search),
          SizedBox(
            width: 10,
          ),
          Icon(Icons.heat_pump_sharp),
          SizedBox(
            width: 10,
          ),
          Icon(Icons.shop_2)
        ],
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              FutureBuilder<List<Autogenerated>>(
                future: futureAlbum,
                builder: (context, snapshot) {
                  if (snapshot.hasData) {
                    return Column(
                      children: [
                        Container(
                          height: 500,
                          width: 500,
                          child: Image.network(snapshot.data![0].image),
                        ),
                        SizedBox(height: 35),
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Text("New Arrivals"),
                        ),
                        SizedBox(height: 20),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            Column(
                              children: [
                                buildImageContainer(snapshot.data![1].image),
                                Text("Shirt")
                              ],
                            ),
                            Column(
                              children: [
                                buildImageContainer(snapshot.data![2].image),
                                Text("Shirt")
                              ],
                            ),
                            Column(
                              children: [
                                buildImageContainer(snapshot.data![3].image),
                                Text("Shirt")
                              ],
                            ),
                          ],
                        ),
                        SizedBox(height: 50),
                        Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Container(
                                  height: 200,
                                  width: 200,
                                  child: Image.network(snapshot.data![4].image),
                                ),
                                SizedBox(
                                  width: 60,
                                ),
                                Container(
                                  height: 100,
                                  width: 100,
                                  child: Text("Benvo Categories"),
                                )
                              ],
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Container(
                              height: 200,
                              width: 200,
                              child: Image.network(snapshot.data![5].image),
                            ),
                            SizedBox(
                              width: 60,
                            ),
                            Container(
                              height: 100,
                              width: 100,
                              child: Image.network(snapshot.data![6].image),
                            )
                          ],
                        ),
                        Column(
                          children: [
                            Container(
                              height: 350,
                              width: 350,
                              child: Image.network(snapshot.data![12].image),
                            )
                          ],
                        )
                      ],
                    );
                  } else if (snapshot.hasError) {
                    return Text('${snapshot.error}');
                  }
                  return const CircularProgressIndicator();
                },
              ),
            ],
          ),
        ),
      ),
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
            const DrawerHeader(
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
              child: Text('Drawer Header'),
            ),
            ListTile(
              title: const Text('Item 1'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('Item 2'),
              onTap: () {},
            ),
          ],
        ),
      ),
    );
  }

  Widget buildImageContainer(String imageUrl) {
    return Container(
      height: 120,
      width: 120,
      child: Image.network(imageUrl),
    );
  }
}
